//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class After extends JPanel {
    private JButton client_logout_button;
    private JTextArea client_active;
    private JLabel client_active_label;
    private JTextArea client_chatlog;
    private JButton client_file_button;
    private JButton client_message_button;
    private JTextArea client_message_field;
    private JScrollPane vertical_log;
    private JScrollPane vertical_user;
    private JScrollPane vertical_message;

    public After() {
        // construct components
        client_logout_button = new JButton("Logout");
        client_active = new JTextArea(5, 5);
        client_active_label = new JLabel("Active Users:");
        client_chatlog = new JTextArea(5, 5);
        client_file_button = new JButton("Send File");
        client_message_button = new JButton("Send Message");

        client_message_field = new JTextArea(5, 5);
        client_message_field.setLineWrap(true);
        client_message_field.setEditable(true);
        client_message_field.setVisible(true);

        // adjust size and set layout
        setPreferredSize(new Dimension(601, 350));
        setLayout(null);

        vertical_message = new JScrollPane(client_message_field);
        vertical_message.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        // add components
        add(client_logout_button);
        add(client_active);
        add(client_active_label);
        add(client_chatlog);
        add(client_file_button);
        add(client_message_button);
        add(vertical_message);

        // set component bounds (only needed by Absolute Positioning)
        client_logout_button.setBounds(480, 20, 100, 25);
        client_active.setBounds(410, 80, 165, 180);
        client_active_label.setBounds(410, 55, 100, 25);
        client_chatlog.setBounds(25, 60, 375, 200);
        client_file_button.setBounds(364, 318, 100, 25);
        client_message_button.setBounds(457, 318, 125, 25);
        vertical_message.setBounds(25, 263, 550, 51);
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("After");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new After());
        frame.pack();
        frame.setVisible(true);
    }
}
